### ISSUE TITLE
Impossibility to launch Minecraft Beta versions

### ISSUE THREAD

**Issue by DelofJ** [MCMrARM/mc-w10-version-launcher#200]
Since Mojang retired the Minecraft Beta system, you can no longer install and play Minecraft Beta builds through the launcher (yes it is a copy paste of [this issue](https://github.com/BedrockLauncher/BedrockLauncher/issues/212) since I use the 2 launchers)

**Comment by DelofJ** [comment]
Edit : Apparently the problem will be fixed on the Bedrock Launcher, maybe it will also be fixed here

**Comment by dktapps** [comment]
Beta versions are no longer available to download from Microsoft servers due to termination of the beta programme (in favour of the Preview app). There's no clear solution to this problem.

The only suggestion I can offer is to scavenge an appx for older betas if you happen to need them, and import them into the launcher, but beware of downloading something dodgy. I don't know of any archives to recommend.
