### ISSUE TITLE
0.14.3 Missing?

### ISSUE THREAD

**Issue by z0mbieslayer** [MCMrARM/mc-w10-version-launcher#85]
Just wondering if 0.14.3 is ever planned to be added, since I think it was the final bug fix update before 0.15

**Comment by dktapps** [comment]
Older versions are provided on an "as-is" basis, because adding them to the launcher requires recovering the version IDs manually to add to https://github.com/MCMrARM/mc-w10-versiondb. Obviously we'd like to have all the versions if it was possible, but this is impractical because of how difficult it is to recover the IDs for old versions.
